FROM python:3.10-alpine3.16

LABEL version="1.0"
LABEL maintainer="MrYazdan.ir <<mrrezayazdani@yahoo.com>>"

ENV LANG en_US.utf8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG PA_PACKAGES
ARG PA_FILENAME

WORKDIR /usr/src/app
COPY . .

RUN apk update \
   && apk add --no-cache --virtual .build-deps \
   ca-certificates gcc linux-headers \
   jpeg-dev zlib-dev musl-dev postgresql-dev \
   ${PA_PACKAGES} \
   && find /usr/local \
       \( -type d -a -name test -o -name tests \) \
       -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
       -exec rm -rf '{}' + \
   && runDeps="$( \
       scanelf --needed --nobanner --recursive /usr/local \
               | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
               | sort -u \
               | xargs -r apk info --installed \
               | sort -u \
   )" \
   && apk add --virtual .rundeps $runDeps \
   && apk del --no-network .build-deps \
   && pip install -U pip \
   && pip install -r ${PA_FILENAME}

STOPSIGNAL SIGINT