FROM python:3.10-alpine3.16

LABEL version="1.0"
LABEL maintainer="MrYazdan.ir <<mrrezayazdani@yahoo.com>>"

ENV LANG en_US.utf8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

FROM alpine:3.16

ENV PATH /usr/local/bin:$PATH
ENV LANG C.UTF-8
ENV PYTHON_VERSION 3.10.7

# runtime dependencies
RUN set -eux; \
	apk add --no-cache ca-certificates tzdata

RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		gnupg tar xz gcc gdbm-dev \
		bluez-dev bzip2-dev dpkg-dev dpkg expat-dev findutils \
		libc-dev libffi-dev libnsl-dev libtirpc-dev linux-headers \
		make ncurses-dev openssl-dev pax-utils readline-dev \
		sqlite-dev tcl-dev tk tk-dev \
		util-linux-dev xz-dev zlib-dev \
	wget -O python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz"; \
	mkdir -p /usr/src/python; \
	tar --extract --directory /usr/src/python --strip-components=1 --file python.tar.xz; \
	rm python.tar.xz; cd /usr/src/python; \
	gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
	./configure \
		--build="$gnuArch" --enable-loadable-sqlite-extensions --enable-optimizations \
		--enable-option-checking=fatal --enable-shared \
		--with-lto --with-system-expat --without-ensurepip; \
	nproc="$(nproc)"; \
	make -j "$nproc" EXTRA_CFLAGS="-DTHREAD_STACK_SIZE=0x100000" LDFLAGS="-Wl,--strip-all"; \
	make install; \
	cd /; rm -rf /usr/src/python; \
	find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
			-o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
		\) -exec rm -rf '{}' + \
	; \
	find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec scanelf --needed --nobanner --format '%n#p' '{}' ';' \
		| tr ',' '\n' | sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
		| xargs -rt apk add --no-network --virtual .python-rundeps \
	; \
	apk del --no-network .build-deps; \
	python3 --version

RUN set -eux; \
	for src in idle3 pydoc3 python3 python3-config; do \
		dst="$(echo "$src" | tr -d 3)"; \
		[ -s "/usr/local/bin/$src" ]; \
		[ ! -e "/usr/local/bin/$dst" ]; \
		ln -svT "$src" "/usr/local/bin/$dst"; \
	done

ENV PYTHON_PIP_VERSION 22.2.2
ENV PYTHON_SETUPTOOLS_VERSION 63.2.0

RUN set -eux; \
	wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py; \
	export PYTHONDONTWRITEBYTECODE=1; \
	python3 get-pip.py --disable-pip-version-check --no-cache-dir --no-compile  "pip==$PYTHON_PIP_VERSION" "setuptools==$PYTHON_SETUPTOOLS_VERSION"; \
	rm -f get-pip.py; \
	pip install -U pip; \
	export PYTHON_PIP_VERSION="$(pip -V | cut -d " " -f 2)"

CMD ["python3"]
